### ISSUE TITLE
Gen 5 PCDs given no description?

### ISSUE THREAD

**Issue by InternalLoss** [AdmiralCurtiss/MysteryGiftConvert#1]
Please prove me wrong if incorrect, but when I tried to convert a lot of Gen 5 files into BINs for distribution, most if not all have this in:
```
00000d0: 4e00 6f00 2000 4400 6500 7300 6300 7200  N.o. .D.e.s.c.r.
00000e0: 6900 7000 7400 6900 6f00 6e00 2000 4100  i.p.t.i.o.n. .A.
00000f0: 7600 6100 6900 6c00 6100 6200 6c00 6500  v.a.i.l.a.b.l.e.
```

These files were sourced from Project Pokémon, so they should have a valid description.

**Comment by AdmiralCurtiss** [comment]
The descriptions aren't stored after being shown on download, so anything extracted from the save file after receiving the Wonder Card instead of actually intercepting/faking the Wonder Card download will not have them. There's a command line option to provide a custom description for those cases.

**Comment by InternalLoss** [comment]
I see, so that's where I guess it'd be time to read bulbapedia. Thank you very much for the explanation c:

Would you be able to also possibly provide a release on /releases for those without access to VS, as this does seem to work under Wine/Mono :3

**Comment by AdmiralCurtiss** [comment]
Sure, no problem. Uploaded a binary to the GitHub releases. (https://github.com/AdmiralCurtiss/MysteryGiftConvert/releases)

**Comment by InternalLoss** [comment]
Thanks! Issue Closed c:
