### ISSUE TITLE
Using with leaked DPDeliever always gives error

### ISSUE THREAD

**Issue by ThatsItForTheOtherOne** [AdmiralCurtiss/MysteryGiftConvert#3]
I'm sure you're surprised as hell anyone is making an issue, but when ripping the MYGs from known good PCDs, using them in the leaked DPDeliever will always result in Pokemon Pearl (JP) saying the mystery gift is not for this version.

I'm trying this over slot 2, is your format correct or am I doing something wrong?

**Comment by ThatsItForTheOtherOne** [comment]
The error is おくりものを　みつけましたが
このバージョンでは▽
うけとることが　できません▽
Ａボタンで　メニューに　もどります

**Comment by AdmiralCurtiss** [comment]
It's entirely possible that that program is expecting a different format or is checking more flags than the NWFC delivery these were used for before. Not sure. You might want to compare the generated files with other files that you have that work, if any.

**Comment by AdmiralCurtiss** [comment]
In case you're unaware, we used this to generate the files for our custom online NWFC server, not for local distribution.

https://github.com/barronwaffles/dwc_network_server_emulator/tree/master/dlc/ADAE

**Comment by ThatsItForTheOtherOne** [comment]
I know it's used for NWFC but this program generates NWFC ROMs and does not work with PCDs, the closest I got with a PCD is bad egg with completely garbage stats. It actually seem to be taking MYGs in some capacity.

**Comment by ThatsItForTheOtherOne** [comment]
It appears I have been wrong and it uses a completely different format all together.

**Comment by AdmiralCurtiss** [comment]
In that case I'll close this, alright?

**Comment by ThatsItForTheOtherOne** [comment]
Yes, I'm firing up Ghidra so I can see if I can find the actual structure.
