### ISSUE TITLE
Not able to convert PCD's in Mass.

### ISSUE THREAD

**Issue by ScarlettHaze** [AdmiralCurtiss/MysteryGiftConvert#4]
I wish there was an option to convert them all in mass from pcd to myg

**Comment by AdmiralCurtiss** [comment]
Try something like `FOR %G IN (*.pcd) DO MysteryGiftConvert %G`.
https://ss64.com/nt/for.html

**Comment by ScarlettHaze** [comment]
I've tried with that and Failed to open file!

**Comment by AdmiralCurtiss** [comment]
Spaces in your filename, perhaps? `FOR %G IN (*.pcd) DO MysteryGiftConvert "%G"`

**Comment by ScarlettHaze** [comment]
Worked! thanks <3
